# Generated by Django 5.2.11 on 2026-02-28 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 28, 6, 48, 37, 347410, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
