# Generated by Django 5.2.11 on 2026-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurywatch', '0002_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
